/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.60.0
  Forc version: 0.44.0
  Fuel-Core version: 0.20.5
*/

export default '0x7400000347000000000000000000003c5dfcc00110fff3005d4060495d47f000134904407648000272f0007b36f000001aec50009100000024040000000000002151bd4b'